export enum Sets {
  NOTHING = 'NOTHING',
  ONE_PAIR = 'ONE PAIR',
  TWO_PAIR = 'TWO PAIR',
  TREE_OF_KIND = 'TREE OF KIND',
  STRAIGHT = 'STRAIGHT',
  FLUSH = 'FLUSH',
  FULL_HOUSE = 'FULL HOUSE',
  FOUR_OF_KIND = 'FOUR OF KIND',
  STRAIGHT_FLUSH = 'STRAIGHT FLUSH',
  ROYAL_FLUSH = 'ROYAL FLUSH',
}
